# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1swvPHVfME9Hn5BvEjpD-vtmangZhV7O1
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
titan=pd.read_csv('/content/train_and_test2.csv')

"""Question 1"""

fig, axes = plt.subplots(figsize=(10,10))
sns.scatterplot(x='Age', y='Fare', data=titan, ax=axes)

"""Question 2"""

sns.lineplot(x="Pclass",y="Fare",data=titan)
plt.show()

"""Question 3"""

titanic_hist = titan.Fare.plot.hist(bins = 40, color = 'red')
plt.xlabel('Fare (pounds, 1912 prices)')
plt.show(titanic_hist)

"""Question 4"""

titanic_pclass_fig, titanic_pclass_ax = plt.subplots()
color = ['red', 'green', 'blue']
count = 0
for name, group in titan.groupby('Pclass'):
  titanic_pclass_ax.plot(group.Age, group.Fare, '.',
label = name, alpha = 0.7,
c = color[count])
count += 1
titanic_pclass_ax.legend(numpoints=1, title = "Passenger class",
fontsize = 10)
plt.xlabel('Age (years)')
plt.ylabel('Fare (pounds, 1912 prices)')
titanic_pclass_ax.set_xlim(-1, 85)
titanic_pclass_ax.set_ylim(-1, 600)
plt.show(titanic_pclass_fig)

"""Question 5"""

pclass_fare_titanic = titan[['Pclass', 'Fare']].pivot(columns =
'Pclass', values = 'Fare')
box_color = dict(boxes = 'black',
whiskers = 'black',
medians = 'red',
caps = 'blue')
titanic_pclass_boxplot = pclass_fare_titanic.plot.box(color =
box_color)
plt.xlabel('Passenger class')
plt.ylabel('Fare')
plt.show(titanic_pclass_boxplot)

"""Question 6"""

contingency_titanic = titan.groupby(['Pclass','sibsp']).size().unstack()
titanic_barplot = contingency_titanic.plot.bar(stacked=True,
color = ["yellow","magenta"])
plt.ylabel("Counts")
plt.xlabel('Passenger class')
plt.xticks(rotation=0)
plt.show(titanic_barplot)